export const itemsNotes = {
  40262997: {
    ResultadoContacto: true,
    PlanRutaAtención: false,
    Servicio: false,
    EtiquetaAdministrativa: false,
    MotivoInasistencia: true,
    ObservacionSeguimiento: true,
    NotaCambioEtiquetaAdministrativa: false,
  },
  40262988: {
    ResultadoContacto: true,
    PlanRutaAtención: false,
    Servicio: false,
    EtiquetaAdministrativa: false,
    MotivoInasistencia: false,
    ObservacionSeguimiento: true,
    NotaCambioEtiquetaAdministrativa: false,
  },
  40262982: {
    ResultadoContacto: true,
    PlanRutaAtención: false,
    Servicio: false,
    EtiquetaAdministrativa: true,
    MotivoInasistencia: false,
    ObservacionSeguimiento: true,
    NotaCambioEtiquetaAdministrativa: true,
  },
  40262957: {
    ResultadoContacto: true,
    PlanRutaAtención: false,
    Servicio: false,
    EtiquetaAdministrativa: false,
    MotivoInasistencia: false,
    ObservacionSeguimiento: true,
    NotaCambioEtiquetaAdministrativa: false,
  },
  40414474: {
    ResultadoContacto: true,
    PlanRutaAtención: true,
    Servicio: true,
    EtiquetaAdministrativa: false,
    MotivoInasistencia: false,
    ObservacionSeguimiento: true,
    NotaCambioEtiquetaAdministrativa: false,
  },
  45323546: {
    ResultadoContacto: true,
    PlanRutaAtención: false,
    Servicio: false,
    EtiquetaAdministrativa: false,
    MotivoInasistencia: false,
    ObservacionSeguimiento: true,
    NotaCambioEtiquetaAdministrativa: false,
  },
  45323551: {
    ResultadoContacto: true,
    PlanRutaAtención: false,
    Servicio: false,
    EtiquetaAdministrativa: false,
    MotivoInasistencia: false,
    ObservacionSeguimiento: true,
    NotaCambioEtiquetaAdministrativa: false,
  },
  null: {
    ResultadoContacto: false,
    PlanRutaAtención: false,
    Servicio: false,
    EtiquetaAdministrativa: false,
    MotivoInasistencia: false,
    ObservacionSeguimiento: false,
    NotaCambioEtiquetaAdministrativa: false,
  },
  undefined: {
    ResultadoContacto: false,
    PlanRutaAtención: false,
    Servicio: false,
    EtiquetaAdministrativa: false,
    MotivoInasistencia: false,
    ObservacionSeguimiento: false,
    NotaCambioEtiquetaAdministrativa: false,
  },
};
